version: "3.7"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"
  mock-particle:
    build:
      context: ./tests/mock-particle
    ports:
      - 8099:8099